# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Default puppet provisioning from vagrant is not used due to errorneous
# support for Puppet 4.x
Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/vivid64"
	config.vm.network "forwarded_port", guest: 1111, host: 8000, host_ip: "127.0.0.1"
	config.vm.synced_folder "../", "/home/vagrant/ScopeIT/"

	config.vm.provision "fix-no-tty", type: "shell" do |s|
	    s.privileged = false
	    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
	end

    config.vm.provision "get-librarian", type: "shell", inline: "gem install librarian-puppet"
    config.vm.provision "get-modules", type: "shell", inline: "librarian-puppet install --verbose"
    config.vm.provision "puppet" do |puppet|
		puppet.manifests_path = "manifests"
	    puppet.manifest_file = "default.pp"
	    puppet.module_path = "modules"
	end
end
